# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Harish Alagappa's portfolio
email: harish@alagappa.in
description: > # this means to ignore newlines until "baseurl:"
  Harish Alagappa's brilliant portfolio. Every text that he's written and published
  is referenced here, and linked to if it was published on the net. In addition, 
  exclusive content is available.
baseurl: "/harish" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: chaosverse
github_username:  aktiur

# Build settings
markdown: kramdown


prose:
  rooturl: '_posts'
  siteurl: 'http://aktiur.github.io/harish/'
  relativeLinks: 'http://aktiur.github.io/harish/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "History"
              value: "history"
            - name: "Climate Change"
              value: "climate"
            - name: "Energy"
              value: "energy"
            - name: "Sports"
              value: "sports"
            - name: "Miscellaneous"
              value: "miscellaneous"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
